[package]
name = "trojan_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
trojan_rust = { git = "https://github.com/qiuzhiqian/trojan_rust.git" }
tokio = { version = "1", features = ["full"] }
regex = "1"