import { Button } from "std-widgets.slint";

component SimpleSwitch inherits Rectangle {
    callback toggled;
    in-out property <string> text;
    in-out property <bool> checked;
    in-out property<bool> enabled <=> touch-area.enabled;
    width: 40px;
    border-width: 1px;
    border-radius: root.height / 2;
    border-color: self.background.darker(25%);
    background: root.enabled ? (root.checked ? #009788: #888888)  : white;
    animate background { duration: 100ms; }

    bubble := Rectangle {
        width: root.height - 8px;
        height: bubble.width;
        border-radius: bubble.height / 2;
        y: 4px;
        x: 4px + a * (parent.width - self.width - 8px);
        property <float> a: root.checked ? 1 : 0;
        background: root.checked ? white : (root.enabled ? #cccccc : gray);
        animate a, background { duration: 200ms; easing: ease;}
    }

    touch-area := TouchArea {
        width: root.width;
        height: root.height;
        clicked => {
            if (root.enabled) {
                root.checked = !root.checked;
                root.toggled();
            }
        }
    }
}

export {SimpleSwitch}
